export const publicEnv = {
  NEXT_PUBLIC_SITE_URL:
    process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_CLOUDINARY_HERO_VIDEO_URL:
    process.env.NEXT_PUBLIC_CLOUDINARY_HERO_VIDEO_URL,
  NEXT_PUBLIC_CLOUDINARY_WORLD_1_VIDEO_URL:
    process.env.NEXT_PUBLIC_CLOUDINARY_WORLD_1_VIDEO_URL,
  NEXT_PUBLIC_CLOUDINARY_WORLD_2_VIDEO_URL:
    process.env.NEXT_PUBLIC_CLOUDINARY_WORLD_2_VIDEO_URL,
} as const;

export type PublicEnv = typeof publicEnv;
