import "server-only";
import { ObjectId, type Collection } from "mongodb";
import { getMongoDb, mongoClientPromise } from "../db/mongodb.ts";
import { giftCardCreateSchema, giftCardSchema, giftCardTransactionCreateSchema, giftCardTransactionSchema, type GiftCard, type GiftCardTransaction } from "../../domain/gift-card/gift-card.schema.ts";
import { AuraError } from "../../lib/errors/aura-error.ts";
import { ERROR_CODES } from "../../lib/errors/error-codes.ts";
import type { GiftCardRepository, IssuedGiftCard } from "./gift-card-repository.ts";
type CardDoc = Omit<GiftCard, "id"> & { _id: ObjectId }; type TxDoc = Omit<GiftCardTransaction, "id"> & { _id: ObjectId };
const card = (d: CardDoc) => { const { _id, ...rest } = d; return giftCardSchema.parse({ ...rest, id: _id.toHexString() }); }; const tx = (d: TxDoc) => { const { _id, ...rest } = d; return giftCardTransactionSchema.parse({ ...rest, id: _id.toHexString() }); };
export class MongoGiftCardRepository implements GiftCardRepository {
  private async cards(): Promise<Collection<CardDoc>> { return (await getMongoDb()).collection<CardDoc>("giftCards"); } private async transactions(): Promise<Collection<TxDoc>> { return (await getMongoDb()).collection<TxDoc>("giftCardTransactions"); }
  async findByCodeHash(hash: string) { const d = await (await this.cards()).findOne({ codeHash: hash }); return d ? card(d) : null; }
  async issue(input: { codeHash: string; initialBalanceMinor: number; currency: string }): Promise<IssuedGiftCard> { const db = await getMongoDb(); const client = await mongoClientPromise; const session = client.startSession(); const rawCode = ""; try { let output!: IssuedGiftCard; await session.withTransaction(async () => { const now = new Date(); const parsed = giftCardCreateSchema.parse({ codeHash: input.codeHash, initialBalanceMinor: input.initialBalanceMinor, remainingBalanceMinor: input.initialBalanceMinor, currency: input.currency, status: "ACTIVE" }); const doc: CardDoc = { ...parsed, _id: new ObjectId(), createdAt: now, updatedAt: now }; await db.collection<CardDoc>("giftCards").insertOne(doc, { session }); const ledger = giftCardTransactionCreateSchema.parse({ giftCardId: doc._id.toHexString(), type: "ISSUE", amountMinor: input.initialBalanceMinor, balanceBeforeMinor: 0, balanceAfterMinor: input.initialBalanceMinor, createdAt: now }); const ledgerDoc: TxDoc = { ...ledger, _id: new ObjectId() }; await db.collection<TxDoc>("giftCardTransactions").insertOne(ledgerDoc, { session }); output = { card: card(doc), rawCode, transaction: tx(ledgerDoc) }; }); return output; } finally { await session.endSession(); } }
  async redeem(cardId: string, amountMinor: number, reference: string) { const db = await getMongoDb(); const client = await mongoClientPromise; const session = client.startSession(); try { let output!: { card: GiftCard; transaction: GiftCardTransaction; redeemedAmountMinor: number }; await session.withTransaction(async () => { const existingTx = await db.collection<TxDoc>("giftCardTransactions").findOne({ reference }, { session }); if (existingTx) { const existingCard = await db.collection<CardDoc>("giftCards").findOne({ _id: new ObjectId(cardId) }, { session }); if (!existingCard) throw new AuraError(ERROR_CODES.NOT_FOUND, "Gift card not found."); output = { card: card(existingCard), transaction: tx(existingTx), redeemedAmountMinor: existingTx.amountMinor }; return; } const before = await db.collection<CardDoc>("giftCards").findOne({ _id: new ObjectId(cardId), status: "ACTIVE", remainingBalanceMinor: { $gt: 0 } }, { session }); if (!before) throw new AuraError(ERROR_CODES.CONFLICT, "Gift card is unavailable."); const redeemAmount = Math.min(amountMinor, before.remainingBalanceMinor); const afterBalance = before.remainingBalanceMinor - redeemAmount; const updated = await db.collection<CardDoc>("giftCards").findOneAndUpdate({ _id: before._id, status: "ACTIVE", remainingBalanceMinor: before.remainingBalanceMinor }, { $set: { remainingBalanceMinor: afterBalance, status: afterBalance === 0 ? "DEPLETED" : "ACTIVE", updatedAt: new Date() } }, { session, returnDocument: "after" }); if (!updated) throw new AuraError(ERROR_CODES.CONFLICT, "Gift card balance changed."); const ledger = giftCardTransactionCreateSchema.parse({ giftCardId: before._id.toHexString(), type: "REDEEM", amountMinor: redeemAmount, balanceBeforeMinor: before.remainingBalanceMinor, balanceAfterMinor: afterBalance, reference, createdAt: new Date() }); const ledgerDoc: TxDoc = { ...ledger, _id: new ObjectId() }; await db.collection<TxDoc>("giftCardTransactions").insertOne(ledgerDoc, { session }); output = { card: card(updated), transaction: tx(ledgerDoc), redeemedAmountMinor: redeemAmount }; }); return output; } finally { await session.endSession(); } }
  async getTransactionByReference(reference: string) { const d = await (await this.transactions()).findOne({ reference }); return d ? tx(d) : null; }
  async count() { return (await this.cards()).countDocuments(); }
}
