import "server-only";
import { ObjectId, type Collection as MongoCollection } from "mongodb";
import { getMongoDb, mongoClientPromise } from "@/server/db/mongodb";
import { inventoryCreateSchema, inventoryReservationSchema, inventorySchema, type Inventory, type InventoryCreateInput, type InventoryReservation } from "@/domain/inventory/inventory.schema";
import { ORDER_STATUS_TRANSITIONS, orderCreateSchema, orderSchema, orderStatusTransitionSchema, type Order, type OrderCreateInput, type OrderStatus } from "@/domain/order/order.schema";
import type { InventoryRepository, OrderRepository } from "./order-inventory-repository";

type InventoryDoc = Inventory & { _id: ObjectId }; type ReservationDoc = Omit<InventoryReservation, "id"> & { _id: ObjectId }; type OrderDoc = Omit<Order, "id"> & { _id: ObjectId };
const toInventory = (row: InventoryDoc) => inventorySchema.parse(row); const toReservation = (row: ReservationDoc) => inventoryReservationSchema.parse({ ...row, id: row._id.toHexString() }); const toOrder = (row: OrderDoc) => orderSchema.parse({ ...row, id: row._id.toHexString() });
export class MongoInventoryRepository implements InventoryRepository {
  private async inventory(): Promise<MongoCollection<InventoryDoc>> { return (await getMongoDb()).collection("inventory"); }
  private async reservations(): Promise<MongoCollection<ReservationDoc>> { return (await getMongoDb()).collection("inventoryReservations"); }
  async create(input: InventoryCreateInput) { const parsed = inventoryCreateSchema.parse(input); const row: InventoryDoc = { ...parsed, _id: new ObjectId() }; await (await this.inventory()).insertOne(row); return toInventory(row); }
  async getByVariantId(variantId: string) { const row = await (await this.inventory()).findOne({ variantId }); return row ? toInventory(row) : null; }
  async listByVariantIds(variantIds: string[]) { if (!variantIds.length) return []; const rows = await (await this.inventory()).find({ variantId: { $in: variantIds } }).toArray(); return rows.map(toInventory); }
  async findActiveByOrderId(orderId: string) { const rows = await (await this.reservations()).find({ orderId, status: "ACTIVE" }).toArray(); return rows.map(toReservation); }
  async reserve(variantId: string, quantity: number, expiresAt: Date, orderId?: string) { if (!Number.isInteger(quantity) || quantity <= 0) throw new Error("Reservation quantity must be a positive integer."); if (expiresAt <= new Date()) throw new Error("Reservation expiry must be in the future."); const session = (await mongoClientPromise).startSession(); const now = new Date(); let created: ReservationDoc | null = null; try { await session.withTransaction(async () => { const result = await (await this.inventory()).findOneAndUpdate({ variantId, available: { $gte: quantity } }, { $inc: { available: -quantity, reserved: quantity, version: 1 }, $set: { updatedAt: now } }, { returnDocument: "after", session }); if (!result) throw new Error("Insufficient inventory or unknown variant."); const row: ReservationDoc = { _id: new ObjectId(), ...(orderId ? { orderId } : {}), variantId, quantity, status: "ACTIVE", expiresAt, createdAt: now, updatedAt: now }; await (await this.reservations()).insertOne(row, { session }); created = row; }); } finally { await session.endSession(); } return toReservation(created!); }
  async release(reservationId: string) { return this.finish(reservationId, "RELEASED"); }
  async commit(reservationId: string) { return this.finish(reservationId, "COMMITTED"); }
  private async finish(reservationId: string, target: "RELEASED" | "COMMITTED") { const session = (await mongoClientPromise).startSession(); let result: ReservationDoc | null = null; try { await session.withTransaction(async () => { const reservation = await (await this.reservations()).findOne({ _id: new ObjectId(reservationId), status: "ACTIVE" }, { session }); if (!reservation) throw new Error("Reservation is missing or no longer active."); const delta = target === "RELEASED" ? { available: reservation.quantity, reserved: -reservation.quantity } : { available: 0, reserved: -reservation.quantity, committed: reservation.quantity }; const inventory = await (await this.inventory()).findOneAndUpdate({ variantId: reservation.variantId, reserved: { $gte: reservation.quantity } }, { $inc: { ...delta, version: 1 }, $set: { updatedAt: new Date() } }, { returnDocument: "after", session }); if (!inventory) throw new Error("Inventory reservation invariant failed."); result = await (await this.reservations()).findOneAndUpdate({ _id: reservation._id, status: "ACTIVE" }, { $set: { status: target, updatedAt: new Date() } }, { returnDocument: "after", session }); }); } finally { await session.endSession(); } return toReservation(result!); }
}
export class MongoOrderRepository implements OrderRepository {
  private async c(): Promise<MongoCollection<OrderDoc>> { return (await getMongoDb()).collection("orders"); }
  async create(input: OrderCreateInput) { const parsed = orderCreateSchema.parse(input); const now = new Date(); const row: OrderDoc = { ...parsed, _id: new ObjectId(), createdAt: now, updatedAt: now }; await (await this.c()).insertOne(row); return toOrder(row); }
  async findByOrderNumber(orderNumber: string) { const row = await (await this.c()).findOne({ orderNumber }); return row ? toOrder(row) : null; }
  async findById(id: string) { const row = await (await this.c()).findOne({ _id: new ObjectId(id) }); return row ? toOrder(row) : null; }
  async listForUser(userId: string) { return (await (await this.c()).find({ userId }).sort({ createdAt: -1, _id: -1 }).toArray()).map(toOrder); }
  async findForUser(userId: string, orderId: string) { const row = await (await this.c()).findOne({ _id: new ObjectId(orderId), userId }); return row ? toOrder(row) : null; }
  async transitionStatus(id: string, from: OrderStatus, to: OrderStatus) { orderStatusTransitionSchema.parse({ from, to }); const row = await (await this.c()).findOneAndUpdate({ _id: new ObjectId(id), status: from }, { $set: { status: to, updatedAt: new Date() } }, { returnDocument: "after" }); if (!row) throw new Error(`Order transition failed: expected ${from}.`); return toOrder(row); }
}
